#ifdef __CLING__
#pragma cling optimize(0)
#endif
void muon_pT_comp_hist()
{
//=========Macro generated from canvas: muon_pT_comp_hist_canv/muon_pT_comp_hist
//=========  (Thu Jun 27 10:05:34 2024) by ROOT version 6.28/04
   TCanvas *muon_pT_comp_hist_canv = new TCanvas("muon_pT_comp_hist_canv", "muon_pT_comp_hist",0,0,1000,800);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   muon_pT_comp_hist_canv->SetHighLightColor(2);
   muon_pT_comp_hist_canv->Range(-30000,-4573.002,157500,24008.26);
   muon_pT_comp_hist_canv->SetFillColor(0);
   muon_pT_comp_hist_canv->SetBorderMode(0);
   muon_pT_comp_hist_canv->SetBorderSize(2);
   muon_pT_comp_hist_canv->SetTickx(1);
   muon_pT_comp_hist_canv->SetTicky(1);
   muon_pT_comp_hist_canv->SetLeftMargin(0.16);
   muon_pT_comp_hist_canv->SetRightMargin(0.2);
   muon_pT_comp_hist_canv->SetTopMargin(0.05);
   muon_pT_comp_hist_canv->SetBottomMargin(0.16);
   muon_pT_comp_hist_canv->SetFrameBorderMode(0);
   muon_pT_comp_hist_canv->SetFrameBorderMode(0);
   
   TH1F *muon_pT_hist__3 = new TH1F("muon_pT_hist__3","muon pT in MeV",50,0,120000);
   muon_pT_hist__3->SetBinContent(0,1644);
   muon_pT_hist__3->SetBinContent(1,2684);
   muon_pT_hist__3->SetBinContent(2,4297);
   muon_pT_hist__3->SetBinContent(3,21504);
   muon_pT_hist__3->SetBinContent(4,5496);
   muon_pT_hist__3->SetBinContent(5,1653);
   muon_pT_hist__3->SetBinContent(6,661);
   muon_pT_hist__3->SetBinContent(7,284);
   muon_pT_hist__3->SetBinContent(8,135);
   muon_pT_hist__3->SetBinContent(9,73);
   muon_pT_hist__3->SetBinContent(10,53);
   muon_pT_hist__3->SetBinContent(11,42);
   muon_pT_hist__3->SetBinContent(12,22);
   muon_pT_hist__3->SetBinContent(13,13);
   muon_pT_hist__3->SetBinContent(14,10);
   muon_pT_hist__3->SetBinContent(15,15);
   muon_pT_hist__3->SetBinContent(16,5);
   muon_pT_hist__3->SetBinContent(17,6);
   muon_pT_hist__3->SetBinContent(18,8);
   muon_pT_hist__3->SetBinContent(20,1);
   muon_pT_hist__3->SetBinContent(21,1);
   muon_pT_hist__3->SetBinContent(23,1);
   muon_pT_hist__3->SetBinContent(27,1);
   muon_pT_hist__3->SetBinContent(28,1);
   muon_pT_hist__3->SetBinContent(34,1);
   muon_pT_hist__3->SetBinContent(35,1);
   muon_pT_hist__3->SetBinContent(42,2);
   muon_pT_hist__3->SetBinContent(51,2);
   muon_pT_hist__3->SetEntries(38616);
   muon_pT_hist__3->SetStats(0);
   muon_pT_hist__3->SetLineWidth(2);
   muon_pT_hist__3->SetMarkerStyle(20);
   muon_pT_hist__3->SetMarkerSize(1.2);
   muon_pT_hist__3->GetXaxis()->SetTitle("muon momentum (GeV)");
   muon_pT_hist__3->GetXaxis()->SetLabelFont(43);
   muon_pT_hist__3->GetXaxis()->SetLabelSize(21);
   muon_pT_hist__3->GetXaxis()->SetTitleSize(21);
   muon_pT_hist__3->GetXaxis()->SetTitleOffset(1.4);
   muon_pT_hist__3->GetXaxis()->SetTitleFont(43);
   muon_pT_hist__3->GetYaxis()->SetLabelFont(43);
   muon_pT_hist__3->GetYaxis()->SetLabelSize(21);
   muon_pT_hist__3->GetYaxis()->SetTitleSize(21);
   muon_pT_hist__3->GetYaxis()->SetTitleOffset(2);
   muon_pT_hist__3->GetYaxis()->SetTitleFont(43);
   muon_pT_hist__3->GetZaxis()->SetLabelFont(43);
   muon_pT_hist__3->GetZaxis()->SetLabelSize(21);
   muon_pT_hist__3->GetZaxis()->SetTitleSize(21);
   muon_pT_hist__3->GetZaxis()->SetTitleOffset(1);
   muon_pT_hist__3->GetZaxis()->SetTitleFont(43);
   muon_pT_hist__3->Draw("HIST");
   
   TH1F *muon_pT_selection_hist__4 = new TH1F("muon_pT_selection_hist__4","muon transverse momentum after selection in MeV",50,0,120000);
   muon_pT_selection_hist__4->SetBinContent(1,1009);
   muon_pT_selection_hist__4->SetBinContent(2,2008);
   muon_pT_selection_hist__4->SetBinContent(3,16113);
   muon_pT_selection_hist__4->SetBinContent(4,4097);
   muon_pT_selection_hist__4->SetBinContent(5,1265);
   muon_pT_selection_hist__4->SetBinContent(6,526);
   muon_pT_selection_hist__4->SetBinContent(7,216);
   muon_pT_selection_hist__4->SetBinContent(8,101);
   muon_pT_selection_hist__4->SetBinContent(9,54);
   muon_pT_selection_hist__4->SetBinContent(10,35);
   muon_pT_selection_hist__4->SetBinContent(11,34);
   muon_pT_selection_hist__4->SetBinContent(12,14);
   muon_pT_selection_hist__4->SetBinContent(13,10);
   muon_pT_selection_hist__4->SetBinContent(14,9);
   muon_pT_selection_hist__4->SetBinContent(15,11);
   muon_pT_selection_hist__4->SetBinContent(16,2);
   muon_pT_selection_hist__4->SetBinContent(17,4);
   muon_pT_selection_hist__4->SetBinContent(18,7);
   muon_pT_selection_hist__4->SetBinContent(20,1);
   muon_pT_selection_hist__4->SetBinContent(21,1);
   muon_pT_selection_hist__4->SetBinContent(23,1);
   muon_pT_selection_hist__4->SetBinContent(27,1);
   muon_pT_selection_hist__4->SetBinContent(28,1);
   muon_pT_selection_hist__4->SetBinContent(35,1);
   muon_pT_selection_hist__4->SetBinContent(51,2);
   muon_pT_selection_hist__4->SetEntries(25523);
   muon_pT_selection_hist__4->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#0000ff");
   muon_pT_selection_hist__4->SetLineColor(ci);
   muon_pT_selection_hist__4->SetLineWidth(2);
   muon_pT_selection_hist__4->SetMarkerStyle(20);
   muon_pT_selection_hist__4->SetMarkerSize(1.2);
   muon_pT_selection_hist__4->GetXaxis()->SetLabelFont(43);
   muon_pT_selection_hist__4->GetXaxis()->SetLabelSize(21);
   muon_pT_selection_hist__4->GetXaxis()->SetTitleSize(21);
   muon_pT_selection_hist__4->GetXaxis()->SetTitleOffset(1.4);
   muon_pT_selection_hist__4->GetXaxis()->SetTitleFont(43);
   muon_pT_selection_hist__4->GetYaxis()->SetLabelFont(43);
   muon_pT_selection_hist__4->GetYaxis()->SetLabelSize(21);
   muon_pT_selection_hist__4->GetYaxis()->SetTitleSize(21);
   muon_pT_selection_hist__4->GetYaxis()->SetTitleOffset(2);
   muon_pT_selection_hist__4->GetYaxis()->SetTitleFont(43);
   muon_pT_selection_hist__4->GetZaxis()->SetLabelFont(43);
   muon_pT_selection_hist__4->GetZaxis()->SetLabelSize(21);
   muon_pT_selection_hist__4->GetZaxis()->SetTitleSize(21);
   muon_pT_selection_hist__4->GetZaxis()->SetTitleOffset(1);
   muon_pT_selection_hist__4->GetZaxis()->SetTitleFont(43);
   muon_pT_selection_hist__4->Draw("HIST SAME");
   
   TLegend *leg = new TLegend(0.64,0.7,0.85,0.8,NULL,"brNDC");
   leg->SetTextFont(43);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("muon_pT_hist","No cuts","lpf");
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.2);
   entry->SetTextFont(42);
   entry=leg->AddEntry("muon_pT_selection_hist","Segment quality cuts","lpf");
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.2);
   entry->SetTextFont(42);
   leg->Draw();
   muon_pT_comp_hist_canv->Modified();
   muon_pT_comp_hist_canv->cd();
   muon_pT_comp_hist_canv->SetSelected(muon_pT_comp_hist_canv);
}
